collections:
  posts:
    output: true
    permalink: /articles/:name

defaults:
  # Set default layout and gemini false
  -
    scope:
      path: ""
    values:
      layout: "default"
  # Use post layouts
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      is_post: true
